import '.././globals.css';
import styles from './layout.module.css';
import type { Metadata } from 'next';
import SideBar from '@/components/SideBar/SideBar';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import { Noto_Sans } from 'next/font/google';
import cn from 'classnames';

const notoSans = Noto_Sans({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(notoSans.className, styles.wrapper)}>
        <SideBar className={styles.sideBar} />
        <Header className={styles.header} />
        <main className={styles.main}> {children}</main>
        <Footer className={styles.footer} />
      </body>
    </html>
  );
}
